"use strict";
(()=>{const A=window.App,$=A.$,e=A.esc,key=i=>i.kind==='task'?`task|${i.task.id}`:[i.source,i.date,i.start,i.title].join('|');
A.items=(all=false)=>{let a=A.S.tasks.filter(t=>!A.done(t)&&t.date).map(t=>({kind:'task',task:t,date:t.date,start:t.startTime||'',end:t.endTime||'',title:t.title,source:t.category,color:A.cat(t.category).color}));for(const c of A.S.calendars){if(c.enabled===false)continue;(c.events||[]).forEach(x=>a.push({kind:'event',date:x.date,start:x.start||'',end:x.end||'',title:x.title||'Événement',source:c.name,color:c.color||'#64748b',location:x.location||''}))}return a.filter(i=>all||!A.S.hidden.includes(key(i))).sort((x,y)=>x.date.localeCompare(y.date)||(x.start||'').localeCompare(y.start||''))};
const erow=i=>`<div class="agendaRow"><div class="agendaBar" style="background:${i.color}"></div><button class="agendaMain" data-event="${e(key(i))}"><div class="agendaTitle">${e(i.title)}</div><div class="agendaMeta">${i.start?`${i.start}${i.end?`–${i.end}`:''} · `:''}${e(i.source)}</div></button><button class="chevron" data-event="${e(key(i))}">›</button></div>`;
function month(){let y=A.month.getFullYear(),m=A.month.getMonth(),s=(new Date(y,m,1).getDay()+6)%7,n=new Date(y,m+1,0).getDate(),all=A.items(),h=`<div class="monthCard"><div class="monthHead"><button class="btn iconOnly" data-mm="-1">‹</button><strong>${new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(A.month)}</strong><button class="btn iconOnly" data-mm="1">›</button></div><div class="week"><div>Lun</div><div>Mar</div><div>Mer</div><div>Jeu</div><div>Ven</div><div>Sam</div><div>Dim</div></div><div class="monthGrid">`;for(let i=0;i<s;i++)h+='<div class="day blank"></div>';for(let d=1;d<=n;d++){let day=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,r=all.filter(i=>i.date===day);h+=`<button class="day ${day===A.ISO()?'today':''}" data-day="${day}"><span class="dayNum">${d}</span>${r.slice(0,3).map(i=>`<span class="monthEvent" style="background:${i.color}">${e(i.title)}</span>`).join('')}</button>`}return h+'</div></div>'}
A.agendaView=()=>{let all=A.items().filter(i=>i.date>=A.ISO()),g={};all.forEach(i=>(g[i.date]??=[]).push(i));let list=Object.entries(g).map(([d,r])=>`<div class="agendaGroup"><div class="agendaDate">${d===A.ISO()?"Aujourd’hui":d===A.plus(1)?'Demain':A.fmt(d)}</div><div class="card list">${r.map(erow).join('')}</div></div>`).join('');return `<div class="agendaToolbar"><div class="viewSwitch"><button id="vl" class="btn ${A.agendaMode==='list'?'active':''}">Liste</button><button id="vm" class="btn ${A.agendaMode==='month'?'active':''}">Mois</button></div><button id="sync" class="btn iconOnly">↻</button><button id="calset" class="btn iconOnly">⚙</button></div><div id="syncInfo" class="infoBanner hidden"></div>${A.agendaMode==='list'?(list||'<div class="card empty">Aucune échéance.</div>'):month()}`};
A.bindAgenda=()=>{$('vl').onclick=()=>{A.agendaMode='list';A.render()};$('vm').onclick=()=>{A.agendaMode='month';A.render()};$('sync').onclick=A.syncCalendars;$('calset').onclick=()=>A.calendarForm(null);document.querySelectorAll('[data-mm]').forEach(b=>b.onclick=()=>{A.month=new Date(A.month.getFullYear(),A.month.getMonth()+Number(b.dataset.mm),1);A.render()});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>A.dayPopup(b.dataset.day));document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>A.eventDetail(b.dataset.event))};
A.dayPopup=d=>{let r=A.items().filter(i=>i.date===d);A.modal(`<div class="modalHead"><h3>${A.fmt(d)}</h3><button class="close" data-close>×</button></div><div class="card list">${r.map(erow).join('')||'<div class="empty">Aucun événement.</div>'}</div><button id="da" class="btn primary full modalBottom">Ajouter une tâche</button>`);document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>A.eventDetail(b.dataset.event));$('da').onclick=()=>A.taskForm(null,d)};
A.eventDetail=id=>{let i=A.items(true).find(x=>key(x)===id);if(!i)return;if(i.kind==='task')return A.taskDetail(i.task.id);A.modal(`<div class="modalHead"><div><h3>${e(i.title)}</h3><div class="modalSub">${A.fmt(i.date)}</div></div><button class="close" data-close>×</button></div>${i.location?`<div class="detailNotes">${e(i.location)}</div>`:''}<button id="hide" class="btn danger full">Retirer de mon agenda</button>`);$('hide').onclick=()=>{if(!A.S.hidden.includes(id))A.S.hidden.push(id);A.save();A.close();A.render()}};
A.syncCalendars=async()=>{let n=$('syncInfo');if(!A.S.calendars.length)return A.toast('Ajoute un calendrier.');n.classList.remove('hidden');n.textContent='Synchronisation…';let ok=0,ko=0;for(const c of A.S.calendars){if(c.enabled===false)continue;try{let r=await fetch('/api/calendar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:c.url})});if(!r.ok)throw 0;let d=await r.json();c.events=d.events||[];ok++}catch(err){ko++}}A.save();n.textContent=ko?`${ok} OK, ${ko} erreur(s).`:`${ok} calendrier(s) à jour.`;setTimeout(A.render,800)};
A.calendarForm=i=>{let c=i==null?{name:'',url:'',color:'#2f6af2'}:A.S.calendars[i];A.modal(`<div class="modalHead"><h3>Calendrier</h3><button class="close" data-close>×</button></div><div class="field"><label>Nom</label><input id="cn" value="${e(c.name)}"></div><div class="field"><label>URL ICS</label><input id="cu" value="${e(c.url||'')}"></div><div class="field"><label>Couleur</label><input id="cc" type="color" value="${c.color}"></div><button id="cs" class="btn primary full">Enregistrer</button>`);$('cs').onclick=()=>{let name=$('cn').value.trim(),url=$('cu').value.trim().replace(/^webcal:/i,'https:');if(!name||!url)return A.toast('Nom et URL requis.');let d={...c,name,url,color:$('cc').value,enabled:c.enabled!==false,events:c.events||[]};i==null?A.S.calendars.push(d):A.S.calendars[i]=d;A.save();A.close();A.render()}};
})();