"use strict";
window.App=(()=>{
const $=id=>document.getElementById(id),K='organisateurV5',uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ISO=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,plus=n=>{let d=new Date();d.setDate(d.getDate()+n);return ISO(d)},D=s=>new Date(s+'T12:00:00'),fmt=s=>new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'numeric',month:'short'}).format(D(s));
const defaults=()=>({tasks:[],categories:[['Coordo','#2f6af2'],['Coordo Com','#8a4de8'],['Coordo PAPS','#28b463'],['Coordo Logistique','#f2a514'],['Coordo Bac','#22b8b2'],['Perso','#64748b']].map(([name,color])=>({name,color})),calendars:[],hidden:[],contacts:[['Jérôme iCloud','j.barletta@icloud.com','Monsieur'],['Jérôme Vauban','j.barletta@vauban.lu','Monsieur'],['N. La Rosa','n.larosa@vauban.lu','Madame'],['A. Le Pannerer','a.lepannerer@vauban.lu','Monsieur'],['P. Tezza','p.tezza@vauban.lu','Monsieur'],['H. De Rosa','h.derosa@vauban.lu','Monsieur'],['P. Perfetto','p.perfetto@vauban.lu','Monsieur'],['H. Lacouque','h.lacouque@vauban.lu','Madame'],['G. Mansouri','g.mansouri@vauban.lu','Madame']].map(([name,email,civility])=>({id:uid(),name,email,civility})),groups:[],mailMode:'pro',teamTone:'normal'});
function load(){try{for(const k of [K,'organisateurV4','organisateurV3','coordoCleanV6']){let x=localStorage.getItem(k);if(x){let s={...defaults(),...JSON.parse(x)};s.groups=s.groups||s.contactGroups||[];s.hidden=s.hidden||s.hiddenCalendarEvents||[];return s}}}catch(e){}return defaults()}
const A={$,uid,esc,ISO,plus,D,fmt,S:load(),route:'home',agendaMode:'list',month:new Date(),selContacts:new Set(),selGroups:new Set()};
A.save=()=>localStorage.setItem(K,JSON.stringify(A.S));A.cat=n=>A.S.categories.find(c=>c.name===n)||{color:'#64748b'};A.done=t=>t.status==='Terminé';A.late=t=>!A.done(t)&&t.date&&t.date<ISO();A.rank=p=>p==='urgent'?0:p==='haute'?1:p==='normale'?2:3;A.due=t=>!t.date?'Sans date':A.late(t)?`${Math.max(1,Math.round((D(ISO())-D(t.date))/864e5))} j de retard`:t.date===ISO()?"Aujourd’hui":t.date===plus(1)?'Demain':fmt(t.date);A.sort=(a,b)=>(A.late(a)!==A.late(b)?(A.late(a)?-1:1):A.rank(a.priority)-A.rank(b.priority))||(a.date||'9999').localeCompare(b.date||'9999');
A.modal=h=>{$('modalRoot').innerHTML=`<div class="modalbg" data-ov><div class="modal">${h}</div></div>`;document.querySelector('[data-ov]').onclick=e=>{if(e.target===e.currentTarget)A.close()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=A.close)};A.close=()=>{$('modalRoot').innerHTML=''};A.toast=m=>{$('toastRoot').innerHTML=`<div class="toast">${esc(m)}</div>`;setTimeout(()=>$('toastRoot').innerHTML='',1800)};
A.download=(data,name,type='application/json')=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
A.render=()=>{let T={home:['Accueil','Organiseur personnel'],tasks:['Tâches','Tout au même endroit'],agenda:['Agenda','Tâches + calendriers externes'],mail:['Mail','Rédiger vite, envoyer proprement'],settings:['Réglages','Personnalisation et sauvegarde']};$('pageTitle').textContent=T[A.route][0];$('pageSubtitle').textContent=T[A.route][1];$('topAction').style.display=['home','tasks','agenda'].includes(A.route)?'inline-flex':'none';$('fab').style.display=['home','tasks','agenda'].includes(A.route)?'flex':'none';$('view').innerHTML=A.route==='home'?A.homeView():A.route==='tasks'?A.tasksView():A.route==='agenda'?A.agendaView():A.route==='mail'?A.mailView():A.settingsView();A.bindView()};
A.nav=r=>{A.route=r;document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===r));A.render();scrollTo({top:0,behavior:'smooth'})};
A.boot=()=>{document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>A.nav(b.dataset.route));$('topAction').onclick=$('fab').onclick=()=>A.taskForm();$('restoreFile').onchange=e=>{if(e.target.files[0])A.restore(e.target.files[0]);e.target.value=''};A.nav('home')};
window.addEventListener('error',e=>{console.error(e.error||e.message);$('toastRoot').innerHTML=`<div class="fatal"><strong>Erreur Organisateur</strong><span>${esc(e.message)}</span><button onclick="location.reload()">Recharger</button></div>`});
return A;
})();